### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by vanesyan** [vanesyan/romanvanesyan.com#1]
***Tracking list of tasks to be done:***
* [ ] **Apps** ([koa](http://koajs.org) based.)

  * [ ] **Main**
    * [ ] **Pages**
      * [ ] **Portfolio**
      * [ ] **About**
    * [ ] **Front-end**

  * [ ] **Blog** (Static generation)
    * [ ] **`.md` based posts**
